Traceback (most recent call last):
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
M_list = [10,10,85]
theta_ini_list = [5,10,10]

for M,theta_ini in zip(M_list,theta_ini_list):
    
    p.simulate([{'t_end':1, 'theta':np.deg2rad(-theta_ini),'M':M},
                {'t_end':50,'f_x':0}],'prev');

    fig, ax = plt.subplots() 
    line, = ax.plot([], [], 'b', lw=2) 
    pivot, = ax.plot(0, 0, 'bo', ms=7) 
    
    bob, = ax.plot([], [], 'ro', ms=(M**(1/3))*5)  

    txt = ax.text(1,0.5,f't = 0 s')
    txt_theta = ax.text(1,0.0,f'$\\theta = 0 ยบ')
    def init():  
        ax.set_xlim(-1.5,1.5)  
        ax.set_ylim(-1.2*L,1) 


    def update(t): 
        pos_x = np.interp(t,p.T[:,0],p.get_values('pos_x'))  
        pos_y = np.interp(t,p.T[:,0],p.get_values('pos_y')) 
        theta = np.interp(t,p.T[:,0],p.get_values('theta')) 
        bob.set_data(pos_x, pos_y)
        txt.set_text(f't = {t:5.1f} s')
        txt_theta.set_text(f'$\\theta$ = {np.rad2deg(theta):5.1f} ยบ')
        x = [0,pos_x]  
        y = [0,pos_y] 
        line.set_data(x, y)    

    Dt_ani = 1/25    
    ani = FuncAnimation(fig, update,frames=np.arange(0,50,Dt_ani),init_func=init,interval=Dt_ani, blit=True);
    writer = PillowWriter(fps=np.ceil(1/Dt_ani))  
    ani.save(f"pendulum_{M:0.0f}kg_{theta_ini:0.0f}deg.png", writer=writer)  
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mUnboundLocalError[0m                         Traceback (most recent call last)
[1;32m~\anaconda3\envs\workenv\lib\site-packages\matplotlib\animation.py[0m in [0;36msaving[1;34m(self, fig, outfile, dpi, *args, **kwargs)[0m
[0;32m    250[0m         [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 251[1;33m             [1;32myield[0m [0mself[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    252[0m         [1;32mfinally[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\envs\workenv\lib\site-packages\matplotlib\animation.py[0m in [0;36msave[1;34m(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs, progress_callback)[0m
[0;32m   1140[0m                     [1;31m# TODO: See if turning off blit is really necessary[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1141[1;33m                     [0manim[0m[1;33m.[0m[0m_draw_next_frame[0m[1;33m([0m[0md[0m[1;33m,[0m [0mblit[0m[1;33m=[0m[1;32mFalse[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1142[0m                     [1;32mif[0m [0mprogress_callback[0m [1;32mis[0m [1;32mnot[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\envs\workenv\lib\site-packages\matplotlib\animation.py[0m in [0;36m_draw_next_frame[1;34m(self, framedata, blit)[0m
[0;32m   1175[0m         [0mself[0m[1;33m.[0m[0m_pre_draw[0m[1;33m([0m[0mframedata[0m[1;33m,[0m [0mblit[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1176[1;33m         [0mself[0m[1;33m.[0m[0m_draw_frame[0m[1;33m([0m[0mframedata[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1177[0m         [0mself[0m[1;33m.[0m[0m_post_draw[0m[1;33m([0m[0mframedata[0m[1;33m,[0m [0mblit[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\envs\workenv\lib\site-packages\matplotlib\animation.py[0m in [0;36m_draw_frame[1;34m(self, framedata)[0m
[0;32m   1725[0m         [1;31m# func needs to return a sequence of any artists that were modified.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1726[1;33m         [0mself[0m[1;33m.[0m[0m_drawn_artists[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_func[0m[1;33m([0m[0mframedata[0m[1;33m,[0m [1;33m*[0m[0mself[0m[1;33m.[0m[0m_args[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1727[0m         [1;32mif[0m [0mself[0m[1;33m.[0m[0m_blit[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m<ipython-input-12-cd037148c7ca>[0m in [0;36mupdate[1;34m(t)[0m
[0;32m     22[0m     [1;32mdef[0m [0mupdate[0m[1;33m([0m[0mt[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 23[1;33m         [0mpos_x[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0minterp[0m[1;33m([0m[0mt[0m[1;33m,[0m[0mp[0m[1;33m.[0m[0mT[0m[1;33m[[0m[1;33m:[0m[1;33m,[0m[1;36m0[0m[1;33m][0m[1;33m,[0m[0mp[0m[1;33m.[0m[0mget_values[0m[1;33m([0m[1;34m'pos_x'[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     24[0m         [0mpos_y[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0minterp[0m[1;33m([0m[0mt[0m[1;33m,[0m[0mp[0m[1;33m.[0m[0mT[0m[1;33m[[0m[1;33m:[0m[1;33m,[0m[1;36m0[0m[1;33m][0m[1;33m,[0m[0mp[0m[1;33m.[0m[0mget_values[0m[1;33m([0m[1;34m'pos_y'[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\workspace\pydae_doc\pendulum\pendulum.py[0m in [0;36mget_values[1;34m(self, name)[0m
[0;32m    550[0m [1;33m[0m[0m
[1;32m--> 551[1;33m         [1;32mreturn[0m [0mvalues[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    552[0m [1;33m[0m[0m

[1;31mUnboundLocalError[0m: local variable 'values' referenced before assignment

During handling of the above exception, another exception occurred:

[1;31mIndexError[0m                                Traceback (most recent call last)
[1;32m<ipython-input-12-cd037148c7ca>[0m in [0;36m<module>[1;34m[0m
[0;32m     34[0m     [0mani[0m [1;33m=[0m [0mFuncAnimation[0m[1;33m([0m[0mfig[0m[1;33m,[0m [0mupdate[0m[1;33m,[0m[0mframes[0m[1;33m=[0m[0mnp[0m[1;33m.[0m[0marange[0m[1;33m([0m[1;36m0[0m[1;33m,[0m[1;36m50[0m[1;33m,[0m[0mDt_ani[0m[1;33m)[0m[1;33m,[0m[0minit_func[0m[1;33m=[0m[0minit[0m[1;33m,[0m[0minterval[0m[1;33m=[0m[0mDt_ani[0m[1;33m,[0m [0mblit[0m[1;33m=[0m[1;32mTrue[0m[1;33m)[0m[1;33m;[0m[1;33m[0m[1;33m[0m[0m
[0;32m     35[0m     [0mwriter[0m [1;33m=[0m [0mPillowWriter[0m[1;33m([0m[0mfps[0m[1;33m=[0m[0mnp[0m[1;33m.[0m[0mceil[0m[1;33m([0m[1;36m1[0m[1;33m/[0m[0mDt_ani[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 36[1;33m     [0mani[0m[1;33m.[0m[0msave[0m[1;33m([0m[1;34mf"pendulum_{M:0.0f}kg_{theta_ini:0.0f}deg.png"[0m[1;33m,[0m [0mwriter[0m[1;33m=[0m[0mwriter[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m~\anaconda3\envs\workenv\lib\site-packages\matplotlib\animation.py[0m in [0;36msave[1;34m(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs, progress_callback)[0m
[0;32m   1143[0m                         [0mprogress_callback[0m[1;33m([0m[0mframe_number[0m[1;33m,[0m [0mtotal_frames[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1144[0m                         [0mframe_number[0m [1;33m+=[0m [1;36m1[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1145[1;33m                 [0mwriter[0m[1;33m.[0m[0mgrab_frame[0m[1;33m([0m[1;33m**[0m[0msavefig_kwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1146[0m [1;33m[0m[0m
[0;32m   1147[0m     [1;32mdef[0m [0m_step[0m[1;33m([0m[0mself[0m[1;33m,[0m [1;33m*[0m[0margs[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\envs\workenv\lib\contextlib.py[0m in [0;36m__exit__[1;34m(self, type, value, traceback)[0m
[0;32m    128[0m                 [0mvalue[0m [1;33m=[0m [0mtype[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    129[0m             [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 130[1;33m                 [0mself[0m[1;33m.[0m[0mgen[0m[1;33m.[0m[0mthrow[0m[1;33m([0m[0mtype[0m[1;33m,[0m [0mvalue[0m[1;33m,[0m [0mtraceback[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    131[0m             [1;32mexcept[0m [0mStopIteration[0m [1;32mas[0m [0mexc[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    132[0m                 [1;31m# Suppress StopIteration *unless* it's the same exception that[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\envs\workenv\lib\site-packages\matplotlib\animation.py[0m in [0;36msaving[1;34m(self, fig, outfile, dpi, *args, **kwargs)[0m
[0;32m    251[0m             [1;32myield[0m [0mself[0m[1;33m[0m[1;33m[0m[0m
[0;32m    252[0m         [1;32mfinally[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 253[1;33m             [0mself[0m[1;33m.[0m[0mfinish[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    254[0m [1;33m[0m[0m
[0;32m    255[0m [1;33m[0m[0m

[1;32m~\anaconda3\envs\workenv\lib\site-packages\matplotlib\animation.py[0m in [0;36mfinish[1;34m(self)[0m
[0;32m    552[0m [1;33m[0m[0m
[0;32m    553[0m     [1;32mdef[0m [0mfinish[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 554[1;33m         self._frames[0].save(
[0m[0;32m    555[0m             [0mself[0m[1;33m.[0m[0moutfile[0m[1;33m,[0m [0msave_all[0m[1;33m=[0m[1;32mTrue[0m[1;33m,[0m [0mappend_images[0m[1;33m=[0m[0mself[0m[1;33m.[0m[0m_frames[0m[1;33m[[0m[1;36m1[0m[1;33m:[0m[1;33m][0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    556[0m             duration=int(1000 / self.fps), loop=0)

[1;31mIndexError[0m: list index out of range
IndexError: list index out of range

